// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  totalOrders:        number;
  paidOrders:         number;
  notPaidOrders:      number;
  totalClients:       number;
  totalProducts:      number;
  productsOutOfStock: number;
  lowInventory:       number;
}
